const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const inr=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const toast=$('[data-toast]');
function say(message){if(!toast)return;toast.textContent=message;toast.hidden=false;clearTimeout(say.t);say.t=setTimeout(()=>toast.hidden=true,2600)}

const menu=$('[data-menu-trigger]'), drawer=$('#mobile-drawer');
menu?.setAttribute('aria-label',menu.getAttribute('aria-label')||'Menu');
$$('.head-action[href]').forEach(link=>{if(link.getAttribute('aria-label'))return;const href=link.getAttribute('href');const content=link.textContent;if(href==='cart.html')link.setAttribute('aria-label','Bag');else if(content.includes('♡'))link.setAttribute('aria-label','Favourites');else if(href==='account.html')link.setAttribute('aria-label','Account')});
function setMenu(open){if(!menu||!drawer)return;menu.setAttribute('aria-expanded',String(open));drawer.hidden=!open;if(open)drawer.querySelector('a')?.focus()}
menu?.addEventListener('click',()=>setMenu(menu.getAttribute('aria-expanded')!=='true'));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menu?.getAttribute('aria-expanded')==='true'){setMenu(false);menu.focus()}});

const currentPage=location.pathname.split('/').pop()||'index.html';
const isCurrent=pages=>pages.includes(currentPage)?' aria-current="page"':'';
const startingBag=$('[data-bag-count]')?.textContent?.trim()||'0';
document.body.insertAdjacentHTML('beforeend',`<nav class="mobile-dock" aria-label="Mobile navigation"><a href="index.html"${isCurrent(['index.html'])}><span aria-hidden="true">⌂</span>Home</a><a href="shop.html"${isCurrent(['shop.html','create.html'])}><span aria-hidden="true">⌕</span>Shop</a><a href="account.html"${isCurrent(['account.html','track.html'])}><span aria-hidden="true">◎</span>Orders</a><a href="cart.html"${isCurrent(['cart.html','checkout.html'])}><span aria-hidden="true">▱</span>Bag <b data-bag-count>${startingBag}</b></a></nav>`);

$$('[data-save]').forEach(b=>{if(b.closest('a'))b.closest('.product-card')?.append(b);b.addEventListener('click',e=>{e.preventDefault();b.classList.toggle('saved');b.setAttribute('aria-pressed',String(b.classList.contains('saved')));b.textContent=b.classList.contains('saved')?'♥':'♡';say(b.classList.contains('saved')?'Saved to favourites.':'Removed from favourites.')} )});
$$('[data-search-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const term=$('input[type="search"]',form)?.value||'';if(document.body.classList.contains('catalog-page'))filterProducts(term);else location.href=`shop.html?q=${encodeURIComponent(term)}`}));
$$('[data-search-form] input[type="search"]').forEach(input=>input.addEventListener('keydown',event=>{if(event.key!=='Enter')return;event.preventDefault();if(document.body.classList.contains('catalog-page'))filterProducts(input.value);else location.href=`shop.html?q=${encodeURIComponent(input.value)}`}));

const cards=$$('[data-product]'), count=$('[data-result-count]'), empty=$('[data-empty]');
function filterProducts(term=''){const words=String(term).toLowerCase().trim().split(/\s+/).filter(Boolean);let visible=0;cards.forEach(card=>{const show=!words.length||words.some(w=>card.dataset.product.includes(w));card.hidden=!show;if(show)visible++});if(count)count.textContent=`${visible} ${visible===1?'style':'styles'}`;if(empty)empty.hidden=visible>0}
$$('[data-filter]').forEach(button=>button.addEventListener('click',()=>{$$('[data-filter]').forEach(b=>b.classList.remove('active'));button.classList.add('active');filterProducts(button.dataset.filter==='all'?'':button.dataset.filter)}));
$('[data-show-all]')?.addEventListener('click',()=>{const input=$('.site-search input');if(input)input.value='';filterProducts('');$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter==='all'))});
if(document.body.classList.contains('catalog-page')){const q=new URLSearchParams(location.search).get('q')||'';const input=$('.site-search input');if(q&&input){input.value=q;filterProducts(q)}}

const creator=$('[data-creator]');
if(creator){
  const state={target:10,unit:449,colour:'Black',image:'assets/tshirt-black.png',file:'',text:''};
  const inputs=$$('[data-size-input]');
  const total=()=>inputs.reduce((sum,input)=>sum+Number(input.value||0),0);
  const unitFor=qty=>qty>=50?389:qty>=25?419:qty>=10?449:499;
  function render(){const qty=total(),valid=qty===state.target;state.unit=unitFor(state.target);$$('[data-selected-count]').forEach(el=>el.textContent=`${qty}/${state.target}`);$('[data-qty-status]').classList.toggle('invalid',!valid);$('[data-qty-status]').querySelector('span').textContent=valid?'Size distribution complete.':qty<state.target?`Add ${state.target-qty} more across the sizes.`:`Remove ${qty-state.target} to match this tier.`;$('[data-summary-qty]').textContent=`${state.target} pieces`;$('[data-summary-colour]').textContent=state.colour;$('[data-summary-unit]').textContent=inr(state.unit);$('[data-summary-total]').textContent=inr(state.target*state.unit);const bulk=state.target>=25;$('[data-bulk]').hidden=!bulk;$('[data-add]').textContent=bulk?'Request bulk quotation':'Add configured item to bag';$('[data-add]').classList.toggle('button-violet',bulk)}
  function distribute(qty){inputs.forEach(i=>i.value='0');const preferred=inputs.find(i=>i.dataset.sizeInput==='M')||inputs[0];preferred.value=String(qty);render()}
  $$('[data-tier]').forEach(button=>button.addEventListener('click',()=>{$$('[data-tier]').forEach(b=>b.classList.remove('active'));button.classList.add('active');state.target=Number(button.dataset.tier);distribute(state.target)}));
  $$('[data-step]').forEach(button=>button.addEventListener('click',()=>{const input=$(`[data-size-input="${button.dataset.step}"]`);const delta=button.dataset.direction==='plus'?1:-1;input.value=String(Math.max(0,Number(input.value||0)+delta));render()}));
  inputs.forEach(input=>input.addEventListener('input',()=>{input.value=String(Math.max(0,Number(input.value||0)));render()}));
  $$('[data-colour]').forEach(button=>button.addEventListener('click',()=>{$$('[data-colour]').forEach(b=>b.classList.remove('active'));button.classList.add('active');state.colour=button.dataset.colour;state.image=button.dataset.image;$('[data-main-image]').src=state.image;$('[data-colour-name]').textContent=state.colour;render()}));
  $$('[data-thumb]').forEach(button=>button.addEventListener('click',()=>{$$('[data-thumb]').forEach(b=>b.classList.remove('active'));button.classList.add('active');$('[data-main-image]').src=button.dataset.thumb}));
  $('[data-artwork]')?.addEventListener('change',event=>{const file=event.target.files?.[0],status=$('[data-upload-state]');if(!file)return;if(file.size>5*1024*1024){event.target.value='';status.hidden=false;status.classList.add('error');status.textContent='This file is over 5 MB. Choose a smaller PNG, JPG, or PDF.';return}state.file=file.name;status.hidden=false;status.classList.remove('error');status.textContent=`✓ ${file.name} attached securely. You can replace it before checkout.`;$('[data-preview-mark]').textContent='YOUR\nARTWORK'});
  $('[data-custom-text]')?.addEventListener('input',event=>{state.text=event.target.value});
  $('[data-pin-check]')?.addEventListener('click',()=>{const pin=$('[data-pin]').value.trim(),message=$('[data-pin-message]');message.style.color=/^\d{6}$/.test(pin)?'var(--green)':'var(--red)';message.textContent=/^\d{6}$/.test(pin)?'Delivery available. Estimate begins after proof approval.':'Enter a valid 6-digit PIN code.'});
  $('[data-add]')?.addEventListener('click',()=>{if(total()!==state.target){$('[data-creator-error]').textContent=`Your size quantities must total exactly ${state.target}.`;$('[data-qty-status]').scrollIntoView({behavior:'smooth',block:'center'});return}const sizes=inputs.filter(i=>Number(i.value)>0).map(i=>`${i.dataset.sizeInput} × ${i.value}`).join(' · ');localStorage.setItem('okina_design05_cart',JSON.stringify({...state,qty:state.target,total:state.target*state.unit,sizes}));location.href=state.target>=25?'quote.html':'cart.html'});
  render();
}

const cartItem=$('[data-cart-item]');
if(cartItem){const saved=JSON.parse(localStorage.getItem('okina_design05_cart')||'null')||{qty:10,unit:449,total:4490,colour:'Black',sizes:'S × 2 · M × 4 · L × 3 · XL × 1',image:'assets/tshirt-black.png'};let qty=saved.qty;const renderCart=()=>{const total=qty*saved.unit;$('[data-cart-image]').src=saved.image;$('[data-cart-config]').textContent=`${saved.colour} · Front centre · DTF print`;$('[data-cart-sizes]').textContent=saved.sizes;$('[data-cart-qty]').textContent=qty;$('[data-cart-price]').textContent=inr(total);$('[data-subtotal]').textContent=inr(total);$('[data-total]').textContent=inr(total+179);$$('[data-bag-count]').forEach(e=>e.textContent='1')};$('[data-cart-plus]').addEventListener('click',()=>{qty++;renderCart()});$('[data-cart-minus]').addEventListener('click',()=>{qty=Math.max(1,qty-1);renderCart()});$('[data-remove]').addEventListener('click',()=>{cartItem.hidden=true;$('[data-cart-layout]').hidden=true;$('[data-empty-bag]').hidden=false;$$('[data-bag-count]').forEach(e=>e.textContent='0')});$('[data-restore]')?.addEventListener('click',()=>{cartItem.hidden=false;$('[data-cart-layout]').hidden=false;$('[data-empty-bag]').hidden=true;renderCart()});$('[data-coupon-apply]')?.addEventListener('click',()=>say('FIRSTORDER applied in this prototype. Final discount is reviewed at payment.'));renderCart()}

const checkout=$('[data-checkout-form]');
checkout?.addEventListener('submit',event=>{event.preventDefault();$$('[data-error-for]').forEach(e=>{e.hidden=true;e.textContent=''});const rules=[['name',v=>v.trim().length>1,'Enter the recipient name.'],['phone',v=>/^\d{10}$/.test(v.trim()),'Enter a 10-digit phone number.'],['email',v=>/^\S+@\S+\.\S+$/.test(v.trim()),'Enter a valid email address.'],['address',v=>v.trim().length>4,'Enter the delivery address.'],['city',v=>v.trim().length>1,'Enter the city.'],['postal',v=>/^\d{6}$/.test(v.trim()),'Enter a valid 6-digit PIN code.']];let first=null;rules.forEach(([name,valid,message])=>{const input=checkout.elements[name],error=$(`[data-error-for="${name}"]`);if(!input||!error)return;if(!valid(input.value)){input.setAttribute('aria-invalid','true');error.textContent=message;error.hidden=false;first||=input}else input.removeAttribute('aria-invalid')});const alert=$('[data-form-alert]');if(first){alert.hidden=false;alert.textContent='Review the highlighted delivery details. Everything else you entered is preserved.';first.focus();return}alert.hidden=true;sessionStorage.setItem('okina_design05_name',checkout.elements.name.value.trim());const submit=$('[data-checkout-submit]');submit.disabled=true;submit.setAttribute('aria-busy','true');submit.textContent='Securing payment…';setTimeout(()=>location.href='confirmation.html',700)});

$('[data-proof-approve]')?.addEventListener('click',()=>{$('[data-proof-card]').innerHTML='<p class="eyebrow">Recorded today · 4:28 PM</p><h2>Proof approved</h2><p>Production can now begin. This approval is saved against proof V1 and order #OK-2408.</p><span class="status">Approved</span>';say('Proof V1 approved. Production has been notified.')});
$('[data-proof-change]')?.addEventListener('click',()=>say('Change request opened. Your current proof and order details remain saved.'));

