<?php

/**
 * Colors Token Configuration
 *
 * @schema
 * [
 *     'name' => string,
 *     'variable' => string,
 *     'hex' => string,
 *     'aliases' => array<string>,
 *     'used_by' => array<string>,
 *     'contrast' => string,
 *     'shades' => array<int, array{shade: string, variable: string, hex: string}>
 * ]
 */
return [
    [
        'name' => 'Brand',
        'variable' => 'var(--color-brand-500)',
        'hex' => '#e83535',
        'aliases' => ['brand', 'red', 'accent', 'primary'],
        'used_by' => ['Primary action highlights', 'Logo elements', 'Active indicator accents'],
        'contrast' => 'AA Compliant (4.5:1+) on White/Light backgrounds',
        'shades' => [
            ['shade' => '50', 'variable' => 'var(--color-brand-50)', 'hex' => '#fff2f2'],
            ['shade' => '100', 'variable' => 'var(--color-brand-100)', 'hex' => '#ffdddd'],
            ['shade' => '200', 'variable' => 'var(--color-brand-200)', 'hex' => '#ffbaba'],
            ['shade' => '300', 'variable' => 'var(--color-brand-300)', 'hex' => '#ff8585'],
            ['shade' => '400', 'variable' => 'var(--color-brand-400)', 'hex' => '#f55555'],
            ['shade' => '500', 'variable' => 'var(--color-brand-500)', 'hex' => '#e83535'],
            ['shade' => '600', 'variable' => 'var(--color-brand-600)', 'hex' => '#c42424'],
            ['shade' => '700', 'variable' => 'var(--color-brand-700)', 'hex' => '#9e1b1b'],
            ['shade' => '800', 'variable' => 'var(--color-brand-800)', 'hex' => '#7a1616'],
            ['shade' => '900', 'variable' => 'var(--color-brand-900)', 'hex' => '#5c1212'],
            ['shade' => '950', 'variable' => 'var(--color-brand-950)', 'hex' => '#360808'],
        ],
    ],
    [
        'name' => 'Ink',
        'variable' => 'var(--color-ink-900)',
        'hex' => '#1a1816',
        'aliases' => ['ink', 'dark', 'brush', 'secondary'],
        'used_by' => ['Sidebar background', 'Primary text hierarchy', 'Borders', 'Layout overlays'],
        'contrast' => 'AAA Compliant (7:1+) on White',
        'note' => 'Warm undertone is artistically derived from the logo\'s brushstroke character. It is intentionally warmer than neutral black to match the crimson accent.',
        'shades' => [
            ['shade' => '50', 'variable' => 'var(--color-ink-50)', 'hex' => '#fafaf9'],
            ['shade' => '100', 'variable' => 'var(--color-ink-100)', 'hex' => '#f5f4f3'],
            ['shade' => '200', 'variable' => 'var(--color-ink-200)', 'hex' => '#e8e6e4'],
            ['shade' => '300', 'variable' => 'var(--color-ink-300)', 'hex' => '#d3d0cd'],
            ['shade' => '400', 'variable' => 'var(--color-ink-400)', 'hex' => '#a8a4a0'],
            ['shade' => '500', 'variable' => 'var(--color-ink-500)', 'hex' => '#77726e'],
            ['shade' => '600', 'variable' => 'var(--color-ink-600)', 'hex' => '#5a5550'],
            ['shade' => '700', 'variable' => 'var(--color-ink-700)', 'hex' => '#403d39'],
            ['shade' => '800', 'variable' => 'var(--color-ink-800)', 'hex' => '#2a2724'],
            ['shade' => '900', 'variable' => 'var(--color-ink-900)', 'hex' => '#1a1816'],
            ['shade' => '950', 'variable' => 'var(--color-ink-950)', 'hex' => '#0e0d0c'],
        ],
    ],
    [
        'name' => 'Neutral Grays',
        'variable' => 'var(--color-neutral-600)',
        'hex' => '#4b5563',
        'aliases' => ['gray', 'slate', 'text', 'border', 'background'],
        'used_by' => ['Body text fallback', 'Borders', 'Layout backgrounds', 'Card containers', 'Input borders'],
        'contrast' => 'AA/AAA Compliant dependent on shade selection (e.g. 700+ for text)',
        'shades' => [
            ['shade' => '50', 'variable' => 'var(--color-neutral-50)', 'hex' => '#f9fafb'],
            ['shade' => '100', 'variable' => 'var(--color-neutral-100)', 'hex' => '#f3f4f6'],
            ['shade' => '200', 'variable' => 'var(--color-neutral-200)', 'hex' => '#e5e7eb'],
            ['shade' => '300', 'variable' => 'var(--color-neutral-300)', 'hex' => '#d1d5db'],
            ['shade' => '400', 'variable' => 'var(--color-neutral-400)', 'hex' => '#9ca3af'],
            ['shade' => '500', 'variable' => 'var(--color-neutral-500)', 'hex' => '#6b7280'],
            ['shade' => '600', 'variable' => 'var(--color-neutral-600)', 'hex' => '#4b5563'],
            ['shade' => '700', 'variable' => 'var(--color-neutral-700)', 'hex' => '#374151'],
            ['shade' => '800', 'variable' => 'var(--color-neutral-800)', 'hex' => '#1f2937'],
            ['shade' => '900', 'variable' => 'var(--color-neutral-900)', 'hex' => '#111827'],
            ['shade' => '950', 'variable' => 'var(--color-neutral-950)', 'hex' => '#030712'],
        ],
    ],
    [
        'name' => 'Success Alert',
        'variable' => 'var(--color-success-600)',
        'hex' => '#059669',
        'aliases' => ['green', 'alert-success', 'emerald'],
        'used_by' => ['Success indicators', 'Completed states', 'Positive feedback banners', 'Valid validations'],
        'contrast' => 'AA Compliant (4.5:1+) on White',
        'shades' => [
            ['shade' => '50', 'variable' => 'var(--color-success-50)', 'hex' => '#ecfdf5'],
            ['shade' => '100', 'variable' => 'var(--color-success-100)', 'hex' => '#d1fae5'],
            ['shade' => '200', 'variable' => 'var(--color-success-200)', 'hex' => '#a7f3d0'],
            ['shade' => '300', 'variable' => 'var(--color-success-300)', 'hex' => '#6ee7b7'],
            ['shade' => '400', 'variable' => 'var(--color-success-400)', 'hex' => '#34d399'],
            ['shade' => '500', 'variable' => 'var(--color-success-500)', 'hex' => '#10b981'],
            ['shade' => '600', 'variable' => 'var(--color-success-600)', 'hex' => '#059669'],
            ['shade' => '700', 'variable' => 'var(--color-success-700)', 'hex' => '#047857'],
            ['shade' => '800', 'variable' => 'var(--color-success-800)', 'hex' => '#065f46'],
            ['shade' => '900', 'variable' => 'var(--color-success-900)', 'hex' => '#064e3b'],
            ['shade' => '950', 'variable' => 'var(--color-success-950)', 'hex' => '#022c22'],
        ],
    ],
    [
        'name' => 'Warning Alert',
        'variable' => 'var(--color-warning-600)',
        'hex' => '#d97706',
        'aliases' => ['amber', 'yellow', 'alert-warning'],
        'used_by' => ['Warning notices', 'Pending states', 'Neutral alerts'],
        'contrast' => 'AA Compliant (3.0:1+) for graphical boundaries',
        'shades' => [
            ['shade' => '50', 'variable' => 'var(--color-warning-50)', 'hex' => '#fffbeb'],
            ['shade' => '100', 'variable' => 'var(--color-warning-100)', 'hex' => '#fef3c7'],
            ['shade' => '200', 'variable' => 'var(--color-warning-200)', 'hex' => '#fde68a'],
            ['shade' => '300', 'variable' => 'var(--color-warning-300)', 'hex' => '#fcd34d'],
            ['shade' => '400', 'variable' => 'var(--color-warning-400)', 'hex' => '#fbbf24'],
            ['shade' => '500', 'variable' => 'var(--color-warning-500)', 'hex' => '#f59e0b'],
            ['shade' => '600', 'variable' => 'var(--color-warning-600)', 'hex' => '#d97706'],
            ['shade' => '700', 'variable' => 'var(--color-warning-700)', 'hex' => '#b45309'],
            ['shade' => '800', 'variable' => 'var(--color-warning-800)', 'hex' => '#92400e'],
            ['shade' => '900', 'variable' => 'var(--color-warning-900)', 'hex' => '#78350f'],
            ['shade' => '950', 'variable' => 'var(--color-warning-950)', 'hex' => '#451a03'],
        ],
    ],
    [
        'name' => 'Danger Alert',
        'variable' => 'var(--color-danger-600)',
        'hex' => '#dc2626',
        'aliases' => ['red', 'error', 'destructive', 'alert-danger'],
        'used_by' => ['Error states', 'Destructive actions', 'Severe alerts', 'Invalid states'],
        'contrast' => 'AA Compliant (4.5:1+) on White',
        'shades' => [
            ['shade' => '50', 'variable' => 'var(--color-danger-50)', 'hex' => '#fef2f2'],
            ['shade' => '100', 'variable' => 'var(--color-danger-100)', 'hex' => '#fee2e2'],
            ['shade' => '200', 'variable' => 'var(--color-danger-200)', 'hex' => '#fecaca'],
            ['shade' => '300', 'variable' => 'var(--color-danger-300)', 'hex' => '#fca5a5'],
            ['shade' => '400', 'variable' => 'var(--color-danger-400)', 'hex' => '#f87171'],
            ['shade' => '500', 'variable' => 'var(--color-danger-500)', 'hex' => '#ef4444'],
            ['shade' => '600', 'variable' => 'var(--color-danger-600)', 'hex' => '#dc2626'],
            ['shade' => '700', 'variable' => 'var(--color-danger-700)', 'hex' => '#b91c1c'],
            ['shade' => '800', 'variable' => 'var(--color-danger-800)', 'hex' => '#991b1b'],
            ['shade' => '900', 'variable' => 'var(--color-danger-900)', 'hex' => '#7f1d1d'],
            ['shade' => '950', 'variable' => 'var(--color-danger-950)', 'hex' => '#450a0a'],
        ],
    ],
];
